# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('euro_rate', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('pound_rates', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
