# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='euro_rate',
            new_name='eur_rate',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='pound_rates',
            new_name='gbp_rate',
        ),
    ]
