# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BTC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('exchange', models.CharField(blank=True, default='', max_length=100)),
                ('period', models.DurationField()),
                ('period_open', models.DecimalField(decimal_places=8, max_digits=18)),
                ('period_close', models.DecimalField(decimal_places=8, max_digits=18)),
                ('period_high', models.DecimalField(decimal_places=8, max_digits=18)),
                ('period_low', models.DecimalField(decimal_places=8, max_digits=18)),
                ('period_volume', models.DecimalField(decimal_places=8, max_digits=18)),
                ('market_cap', models.DecimalField(decimal_places=8, max_digits=18)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ETH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('exchange', models.CharField(blank=True, default='', max_length=100)),
                ('period', models.DurationField()),
                ('period_open', models.DecimalField(decimal_places=8, max_digits=18)),
                ('period_close', models.DecimalField(decimal_places=8, max_digits=18)),
                ('period_high', models.DecimalField(decimal_places=8, max_digits=18)),
                ('period_low', models.DecimalField(decimal_places=8, max_digits=18)),
                ('period_volume', models.DecimalField(decimal_places=8, max_digits=18)),
                ('market_cap', models.DecimalField(decimal_places=8, max_digits=18)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'ordering': ('created',),
            },
        ),
    ]
