# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btc',
            name='period',
        ),
        migrations.RemoveField(
            model_name='btc',
            name='period_close',
        ),
        migrations.RemoveField(
            model_name='btc',
            name='period_high',
        ),
        migrations.RemoveField(
            model_name='btc',
            name='period_low',
        ),
        migrations.RemoveField(
            model_name='btc',
            name='period_open',
        ),
        migrations.RemoveField(
            model_name='btc',
            name='period_volume',
        ),
        migrations.RemoveField(
            model_name='eth',
            name='period',
        ),
        migrations.RemoveField(
            model_name='eth',
            name='period_close',
        ),
        migrations.RemoveField(
            model_name='eth',
            name='period_high',
        ),
        migrations.RemoveField(
            model_name='eth',
            name='period_low',
        ),
        migrations.RemoveField(
            model_name='eth',
            name='period_open',
        ),
        migrations.RemoveField(
            model_name='eth',
            name='period_volume',
        ),
        migrations.AddField(
            model_name='btc',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='eth',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='btc',
            name='market_cap',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='eth',
            name='market_cap',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
    ]
