# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_auto_20170605_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('exchange', models.CharField(blank=True, default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('market_cap', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
            ],
            options={
                'abstract': False,
                'ordering': ('created',),
            },
        ),
        migrations.RemoveField(
            model_name='btc',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='eth',
            name='owner',
        ),
    ]
