# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 07:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_auto_20170605_2024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='btc',
            options={'ordering': ('date',)},
        ),
        migrations.AlterModelOptions(
            name='eth',
            options={'ordering': ('date',)},
        ),
        migrations.AlterModelOptions(
            name='ltc',
            options={'ordering': ('date',)},
        ),
        migrations.RemoveField(
            model_name='btc',
            name='created',
        ),
        migrations.RemoveField(
            model_name='eth',
            name='created',
        ),
        migrations.RemoveField(
            model_name='ltc',
            name='created',
        ),
        migrations.AddField(
            model_name='btc',
            name='date',
            field=models.DateField(default=datetime.date(2017, 6, 6)),
        ),
        migrations.AddField(
            model_name='eth',
            name='date',
            field=models.DateField(default=datetime.date(2017, 6, 6)),
        ),
        migrations.AddField(
            model_name='ltc',
            name='date',
            field=models.DateField(default=datetime.date(2017, 6, 6)),
        ),
    ]
