# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AAPL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('market_cap', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
            ],
            options={
                'ordering': ('date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FANG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('market_cap', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
            ],
            options={
                'ordering': ('date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('market_cap', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
            ],
            options={
                'ordering': ('date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GOOG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('market_cap', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
            ],
            options={
                'ordering': ('date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NFLX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('market_cap', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
            ],
            options={
                'ordering': ('date',),
                'abstract': False,
            },
        ),
    ]
