# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMZN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('market_cap', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
            ],
            options={
                'abstract': False,
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='FAMGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('market_cap', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
            ],
            options={
                'abstract': False,
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='MSFT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('market_cap', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
            ],
            options={
                'abstract': False,
                'ordering': ('date',),
            },
        ),
    ]
