# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_sandp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SandP',
            new_name='SPX',
        ),
    ]
